### ISSUE TITLE
Suggestion of adding input and output specifications to each tool's doc

### ISSUE THREAD

**Issue by kinzlaw** [FredHutch/gig-map#13]
It seems that I don't have Edit permission to the wiki now.

I suggest adding `input` and `output` specifications to each tool's doc, especially for the `3. Deduplicate your genes` and `4. Aligning genes to genomes` parts for the tutorial. 

I guess this was one of the main faults in my previous invocation, such that the final result didn't include our local genes. I was thinking that intermediate data would be used by tools by implication. I didn't know that I need to pass the result of deduplication to align, I even didn't know what `centroids.faa.gz` was all about.

**Comment by sminot** [comment]
That's a great suggestion! I went through and updated those in the wiki (e.g. https://github.com/FredHutch/gig-map/wiki/deduplicating-genes)
