### ISSUE TITLE
Questions about CPU/memory params

### ISSUE THREAD

**Issue by kinzlaw** [FredHutch/gig-map#14]
Using the current version of code, I run into trouble with `reorganize_fastas.py`, the error looks something like this.
```
Command error:
  .command.sh: line 9:    30 Killed                  reorganize_fastas.py

Work dir:
  /home/cloudam/work/wb/3/work/7b/01b9894c59db2884f4daa4c0ce4432

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```
But `.command.out` is empty. After attaching to the running docker and running `reorganize_fastas.py` manually, I see it gets killed randomly at different numbers of `Reading in` input file(about 310-320 files) logs, so it would be an out of memory problem.

So `question 1`: The default value of `io_limited`(1GB) is somewhat lower for a group of more than 300 genomes.

`Question 2`: In my little experience, I saw that the CPU and memory params impact the concurrency of the running tasks very much, so as the hardware utilization ratio: 

For example(numbers are not quite accurate here), if we have 8 CPU cores and 160GB mem hardware. 
-If we set the params to 8CPU and 160GB, then only 1 process will be run.
-If we set the params to 8CPU and 10GB, then only 1 process will be run.
-If we set the params to 2CPU and 160GB, then only 1 process will be run.
-If we set the params to 1CPU and 10GB, then approximately 8 processes will be run.
-If we set the params to 1CPU and 40GB, then approximately 4 processes will be run.
-If we set the params to 4CPU and 10GB, then approximately 2 processes will be run.

And I see for most of the steps(still with our 350 genomes of data), we can safely set memory param to 3GB or lower, to maximize the processing speed. So to speak, we should set the params to some reasonable value, to ensure that a single process won't fail, as small as possible. In particular, we shouldn't use these params as hardware requirements(such as a memory param of 100GB, telling the user that he must have 100GB installed).

I wish these params be tested more thoroughly and documented in more detail, thanks.

**Comment by sminot** [comment]
Thanks for diving into this. The resources available to each user is generally quite different, for example, I run almost all of my analysis either on AWS Batch or an on-prem SLURM cluster.

I would recommend that you implement whatever balance of resources you find the most useful, customizing a `nextflow.config` file in your home directory to meet your needs. Feel free to reopen this issue if you run into any issues with that.
