### ISSUE TITLE
Wiki edit permission

### ISSUE THREAD

**Issue by kinzlaw** [FredHutch/gig-map#3]
Hi, all.
I'm trying to install gig-map, and found some typos in the wiki doc, for example
![图片](https://user-images.githubusercontent.com/4575752/148039796-e0aa2192-dc18-4d22-96b1-43b73ee76a49.png)

I want to help correcting these.
Since either pull / push the wiki pages and edit using other editor, or write some errata to let you edit the wiki, is somewhat ineffective, I'm  wondering if I can edit the doc directly? Github has the following options(add me to the collaborators, or make the wiki publicly editable), for reference. Thanks.
![图片](https://user-images.githubusercontent.com/4575752/148040743-15936f8b-b61c-4202-8c46-59699cecc6b2.png)

**Comment by sminot** [comment]
Thanks for reaching out and offering to help edit the wiki!

I'd like to make it easy for helpful people like yourself to contribute to this resource, and so I've just changed the settings so that you should be able to make your changes directly to the wiki. 

I'm not sure how easy it will be to moderate content with this feature, but I'm willing to give it a try and see how things go!

Please do reopen this issue if you find that you are not able to actually edit the wiki.

**Comment by kinzlaw** [comment]
Yes, I can now edit the wiki directly within Github. 
But as Github doesn't support editing the markdown content in the `Preview`, it surely isn't as efficient as I thought, later I would try the Pull Request approach(at least editors such as VS Code has side-by-side view, and I can do a compare before commit), let's see if it's okay for you to review every time before the change takes effect.
![图片](https://user-images.githubusercontent.com/4575752/148111046-3dbd2539-2fd7-4574-9c4a-a0ed7e515b10.png)

**Comment by sminot** [comment]
This open setup seems like a reasonable solution for now. Let me know if this ends up being too inconvenient for the changes that you'd like to make and we can reassess.

**Comment by kinzlaw** [comment]
It seems that I don't have Edit permission to the wiki now.

I suggest adding `input` and `output` specifications to each tool, especially for the `3. Deduplicate your genes` and `4. Aligning genes to genomes` parts for the tutorial. 

I guess this was one of the main faults in my previous invocation, such that the final result didn't include our local genes. I was thinking that intermediate data would be used by tools by implication. I didn't know that I need to pass the result of deduplication to align, I even don't know what `centroids.faa.gz` was about.
