### ISSUE TITLE
Instructions to Setup a Docker Environment

### ISSUE THREAD

**Issue by kinzlaw** [FredHutch/gig-map#5]
Hi, Sam.
As documented in the [Install Docker ](https://github.com/FredHutch/gig-map/wiki/Getting-Started#install-docker-for-local-execution-only),
> If gig-map is being run on a standalone computer such as a personal computer or a dedicated lab server, the simplest way to support this behavior is to install [Docker Desktop](https://www.docker.com/products/docker-desktop) and configure Nextflow to use Docker as described below.

But the following of the wiki is mainly about running gig-map locally and directly(without docker) through Nextflow on Linux, which doesn't seem to guide us on how to run a docker build. And I've found some [errors](https://github.com/FredHutch/gig-map/pull/4) following the wiki steps, guessing those errors won't appear in docker.
The only info that I can find is [this quay link](https://quay.io/repository/hdc-workflows/gig-map) in the README.md, but there's also no instructions.
Is the docker approach the `officially supported` one to run gig-map? If so, I'd recommend giving us some related doc(some simple command line/script is helpful).
Thanks.

**Comment by sminot** [comment]
Great question!

There is actually no need to run any `docker build` steps, since all of the images are already available online. As long as Docker is installed and enabled (`-with-docker`), then all software dependencies will be used from those images (as coordinated by Nextflow itself).

**Comment by kinzlaw** [comment]
Great to see the new change of the wiki! We'll try the docker approach for the following research.
